spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://giljob.csznyn6he6hi.ap-northeast-2.rds.amazonaws.com:3306/giljob
    username: giljob
    password: yapp2021!
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  social:
    kakao: https://kapi.kakao.com/v2/user/me
    tokenTime: 2592000000

cloud:
  aws:
    s3:
      bucket: giljob
    credentials:
      access-key: AKIARARMA76PMY6YT2AP
      secret-key: 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
    stack:
      auto: false
    region:
      static: us-east-2