on:
  push:
    branches:
      - develop
  workflow_dispatch:

name: Deploy Spring boot to Amazon EC2
env:
  PROJECT_NAME: giljob

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://giljob-s3/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name GiljobCodeDeploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name GiljobDeployGroup --s3-location bucket=giljob-s3,bundleType=zip,key=$GITHUB_SHA.zip